version: '3.4'
services:
  adminer:
    container_name: planisense-adminer
    image: adminer:4.8.1
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DESIGN: hydra
    ports:
      - '8080:8080'
    networks:
      - planisense

  postgres:
    container_name: planisense_database
    image: postgres
    env_file:
      - ./.env.postgres
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - planisense
    restart: on-failure

networks:
  planisense:
volumes:
  postgres:
